### ISSUE TITLE
I can't verify my email or my web config

### ISSUE THREAD

**Issue by gIsForGravity** [jc9108/eternity#3]
Whenever I try to verify my web config, it just starts loading indefinitely, and when I try to confirm my email, the email is directed towards u/null instead of my actual username. Also, when I open the link in the email, I just get a page saying "fail".

**Comment by jc9108** [comment]
do you have javascript disabled?

**Comment by jc9108** [comment]
do you have javascript and/or websockets disabled? those are required for eternity to work

**Comment by generalpask** [comment]
Having the same issue except I don't get a verification email. Websockets and js are both enabled.

**Comment by jc9108** [comment]
@generalpask i dont think you are having the same issue. i looked at the logs and a verification email for a non-null username was successfully sent to an email containing your name on your github profile (3 times within a 10-minute period). please check your junk/spam folder and email blocking rules!

**Comment by generalpask** [comment]
@jc9108 My bad, the mail was in the spam folder. That's a bit of an embarrassing miss from my side :) Also I tried validating again with a new key and was able to proceed. Cheers
