### ISSUE TITLE
Eternity won't update

### ISSUE THREAD

**Issue by BigMoon500** [jc9108/eternity#5]
I used eternity as usual for a couple of months until just a few weeks ago when it stopped updating with new data. There are no new saved posts, upvoted posts, etc. I tried checking firebase and it seemed normal so I'm not sure what went wrong. If anyone could help that would be greatly appreciated.

**Comment by jc9108** [comment]
the service is operational and running normally; i will need your reddit username to check why your eternity account isnt updating. unless you want to share it here publicly, you can email eternity@portals.sh with your username and refer to this issue there instead.

**Comment by jc9108** [comment]
the service is operational and running normally; i will need your reddit username to check why your eternity account isnt updating. unless you want to share it here publicly, you can email [eternity@portals.sh](mailto:eternity@portals.sh) with your username and refer to this issue there instead.

**Comment by michaelchany** [comment]
Hello, I'm having this issue (and I apologize for opening a discussion).

I will email my username to that address above.

**Comment by jc9108** [comment]
fixed with https://github.com/jc9108/eternity/commit/0be596f11cf7c2d19b7cf9fd3d8e7947fc3ef8a6. however, anything from when it stopped updating till now will not have been saved to your eternity db. if you want to recover those items, you can import a reddit data request (sry for the inconvenience)
