### ISSUE TITLE
Verify email = fail

### ISSUE THREAD

**Issue by Dunkscellos-01** [jc9108/eternity#6]
Hi,

I’ve tried doing this a few times. No matter if I start from the beginning or use a different browser, I get “fail” every-time I reach the email stage.

Thanks.

**Comment by jc9108** [comment]
hi. you need to click on the verification link inside the email while the setup page is still open, as it says in the alert under the input box. so, open the email in another tab or on your phone. you don't need to start over with the firebase stuff, just use the same info.

**Comment by jc9108** [comment]
hi. you need to click on the verification link inside the email while the setup page is still open, as it says in the alert under the input box. so, open the email in another tab or on your phone. you don't need to start over with the firebase stuff, just use the same info.

**Comment by Dunkscellos-01** [comment]
Hi. Yes. I’m following the instructions as outlined. All return “fail.”

**Comment by jc9108** [comment]
do you have javascript or websockets disabled on the site?

**Comment by jc9108** [comment]
do you have javascript or websockets disabled on the site? #3

**Comment by Dunkscellos-01** [comment]
Validation is fine for account key file and API. I’m using Safari stock. I’ve also tried with Chrome stock, as well.

**Comment by Dunkscellos-01** [comment]
I rechecked. Yes, both are enabled.

**Comment by jc9108** [comment]
can you open the devtools console `ctrl+shift+j`, then click the verify email button, and see if any errors show up in the console?

**Comment by Dunkscellos-01** [comment]
Tried a different device. Got it to authenticate. So OK. 

I think there may be issues on mobile devices. Tablets, phones, etc. I didn’t look for errors though, didn’t want to connect my ipad to my laptop to inspect debug errors. Sorry.

**Comment by jc9108** [comment]
ok great.

**Comment by jc9108** [comment]
> I think there may be issues on mobile devices. Tablets, phones, etc. I didn’t look for errors though, didn’t want to connect my ipad

maybe on ios then (i dont have an ios device). ive tested it on android and it works.

hmm but the main application works on ios right?

**Comment by Dunkscellos-01** [comment]
Yeah. Works fine.
